# Bangalore House Price Prediction - Outlier Detection

This notebook only train ML model on different ml algorithms

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

In [3]:
df = pd.read_csv('ohe_data_reduce_cat_class.csv')

In [4]:
df.shape

(7120, 108)

In [5]:
df.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  location_Whitefield  \
0                    0                           1                    0   
1                    0                           1                    0   
2                    0                           1                    0   
3                    0                           1                    0   
4                    1                           1                    0   

   location_Sarjapur  Road  location_Electronic City  \
0                        0                         0   
1                        0                         0   
2                        0                         0   
3                        0                         0   
4                        0                         0   

   location_Raja Rajeshwari Nagar  location_Haralur Road  \
0                               0                      0   
1                               0                      0   
2                               0                      0   
3                               0                      0   
4                               0                      0   

   location_Marathahalli  location_Bannerghatta Road  location_Hennur Road  \
0                      0                           0                     0   
1                      0                           0                     0   
2                      0                           0                     0   
3                      0                           0                     0   
4                      0                           0                     0   

   location_Uttarahalli  location_Thanisandra  \
0                     0                     0   
1                     0                     0   
2                     0                     0   
3                     0                     0   
4                     0                     0   

   location_Electronic City Phase II  location_Hebbal  \
0                                  0                0   
1                                  0                0   
2                                  0                0   
3                                  0                0   
4                                  0                0   

   location_7th Phase JP Nagar  location_Yelahanka  location_Kanakpura Road  \
0                            0                   0                        0   
1                            0                   0                        0   
2                            0                   0                        0   
3                            0                   0                        0   
4                            0                   0                        0   

   location_KR Puram  location_Sarjapur  location_Rajaji Nagar  \
0                  0                  0                      0   
1                  0                  0                      0   
2                  0                  0                      0   
3                  0                  0                      0   
4                  0                  0                      0   

   location_Bellandur  location_Kasavanhalli  location_Begur Road  \
0                   0                      0          

## Split Dataset in train and test

In [6]:
X = df.drop("price", axis=1)
y = df['price']
print('Shape of X = ', X.shape)
print('Shape of y = ', y.shape)

Shape of X =  (7120, 107)
Shape of y =  (7120,)


In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 51)
print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (5696, 107)
Shape of y_train =  (5696,)
Shape of X_test =  (1424, 107)
Shape of y_test =  (1424,)


## Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)
X_train= sc.transform(X_train)
X_test = sc.transform(X_test)

## Machine Learning Model Training

## Linear Regression

In [9]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error
lr = LinearRegression()
lr_lasso = Lasso()
lr_ridge = Ridge()

In [10]:
def rmse(y_test, y_pred):
  return np.sqrt(mean_squared_error(y_test, y_pred))

In [11]:
lr.fit(X_train, y_train)
lr_score = lr.score(X_test, y_test) # with all num var 0.7842744111909903
lr_rmse = rmse(y_test, lr.predict(X_test))
lr_score, lr_rmse

(0.7903837092682258, 64.89843531105598)

In [12]:
# Lasso 
lr_lasso.fit(X_train, y_train)
lr_lasso_score=lr_lasso.score(X_test, y_test) # with balcony 0.5162364637824872
lr_lasso_rmse = rmse(y_test, lr_lasso.predict(X_test))
lr_lasso_score, lr_lasso_rmse

(0.8036372945395598, 62.81324265695799)

## Support Vector Machine

In [13]:
from sklearn.svm import SVR
svr = SVR()
svr.fit(X_train,y_train)
svr_score=svr.score(X_test,y_test) # with 0.2630802200711362
svr_rmse = rmse(y_test, svr.predict(X_test))
svr_score, svr_rmse

(0.20638035840828173, 126.27806378079055)

## Random Forest Regressor

In [14]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor()
rfr.fit(X_train,y_train)
rfr_score=rfr.score(X_test,y_test) # with 0.8863376025408044
rfr_rmse = rmse(y_test, rfr.predict(X_test))
rfr_score, rfr_rmse

(0.8896314787880675, 47.0916949578634)

## XGBoost

In [15]:
import xgboost
xgb_reg = xgboost.XGBRegressor()
xgb_reg.fit(X_train,y_train)
xgb_reg_score=xgb_reg.score(X_test,y_test) # with 0.8838865742273464
xgb_reg_rmse = rmse(y_test, xgb_reg.predict(X_test))
xgb_reg_score, xgb_reg_rmse

(0.8866071985706575, 47.73252984729787)

In [16]:
print(pd.DataFrame([{'Model': 'Linear Regression','Score':lr_score, "RMSE":lr_rmse},
              {'Model': 'Lasso','Score':lr_lasso_score, "RMSE":lr_lasso_rmse},
              {'Model': 'Support Vector Machine','Score':svr_score, "RMSE":svr_rmse},
              {'Model': 'Random Forest','Score':rfr_score, "RMSE":rfr_rmse},
              {'Model': 'XGBoost','Score':xgb_reg_score, "RMSE":xgb_reg_rmse}],
             columns=['Model','Score','RMSE']))

                    Model     Score        RMSE
0       Linear Regression  0.790384   64.898435
1                   Lasso  0.803637   62.813243
2  Support Vector Machine  0.206380  126.278064
3           Random Forest  0.889631   47.091695
4                 XGBoost  0.886607   47.732530


## Cross Validation

In [17]:
from sklearn.model_selection import KFold,cross_val_score
cvs = cross_val_score(xgb_reg, X_train,y_train, cv = 10)
cvs, cvs.mean() # 0.9845963377450353)

(array([0.98991766, 0.98632505, 0.99685279, 0.98296558, 0.97656955,
        0.99525125, 0.97360094, 0.94556716, 0.99408487, 0.98854857]),
 0.9829683423733027)

In [18]:
cvs_rfr = cross_val_score(rfr, X_train,y_train, cv = 10)
cvs_rfr, cvs_rfr.mean() # 0.9652425691235843)

(array([0.99596127, 0.96097551, 0.99669306, 0.96729012, 0.96257244,
        0.93223013, 0.93798211, 0.9043382 , 0.99638693, 0.98666095]),
 0.9641090720890068)

In [19]:
cvs_rfr2 = cross_val_score(RandomForestRegressor(), X_train,y_train, cv = 10)
cvs_rfr2, cvs_rfr2.mean() # 0.9652425691235843)

(array([0.99282976, 0.97415382, 0.99744915, 0.96747391, 0.96525151,
        0.94705835, 0.92806008, 0.91506781, 0.99679588, 0.98169916]),
 0.9665839421807529)

# Hyper Parmeter Tuning

In [20]:
## from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import GridSearchCV
from xgboost.sklearn import XGBRegressor
# Various hyper-parameters to tune
xgb1 = XGBRegressor()
parameters = {'learning_rate': [0.1,0.03, 0.05, 0.07], #so called `eta` value, # [default=0.3] Analogous to learning rate in GBM
              'min_child_weight': [1,3,5], #[default=1] Defines the minimum sum of weights of all observations required in a child.
              'max_depth': [4, 6, 8], #[default=6] The maximum depth of a tree,
              'gamma':[0,0.1,0.001,0.2], #Gamma specifies the minimum loss reduction required to make a split.
              'subsample': [0.7,1,1.5], #Denotes the fraction of observations to be randomly samples for each tree.
              'colsample_bytree': [0.7,1,1.5], #Denotes the fraction of columns to be randomly samples for each tree.
              'objective':['reg:linear'], #This defines the loss function to be minimized.
 
              'n_estimators': [100,300,500]}
 
xgb_grid = GridSearchCV(xgb1,
                        parameters,
                        cv = 2,
                        n_jobs = -1,
                        verbose=True)
 
xgb_grid.fit(X_train, y_train)
 
print(xgb_grid.best_score_) # 0.9397345161940295
print(xgb_grid.best_params_)

Fitting 2 folds for each of 3888 candidates, totalling 7776 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:   27.2s
[Parallel(n_jobs=-1)]: Done 184 tasks      | elapsed:  2.8min
[Parallel(n_jobs=-1)]: Done 434 tasks      | elapsed:  6.3min
[Parallel(n_jobs=-1)]: Done 784 tasks      | elapsed: 11.7min
[Parallel(n_jobs=-1)]: Done 1234 tasks      | elapsed: 18.2min
[Parallel(n_jobs=-1)]: Done 1784 tasks      | elapsed: 26.4min
[Parallel(n_jobs=-1)]: Done 2434 tasks      | elapsed: 36.0min
[Parallel(n_jobs=-1)]: Done 3184 tasks      | elapsed: 49.1min
[Parallel(n_jobs=-1)]: Done 4034 tasks      | elapsed: 65.0min
[Parallel(n_jobs=-1)]: Done 4984 tasks      | elapsed: 82.2min
[Parallel(n_jobs=-1)]: Done 7761 out of 7776 | elapsed: 85.2min remaining:    9.8s
[Parallel(n_jobs=-1)]: Done 7776 out of 7776 | elapsed: 85.2min finished


[23:33:49] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/objective/regression_obj.cu:170: reg:linear is now deprecated in favor of reg:squarederror.
0.9536800131586882
{'colsample_bytree': 1, 'gamma': 0.2, 'learning_rate': 0.05, 'max_depth': 4, 'min_child_weight': 3, 'n_estimators': 500, 'objective': 'reg:linear', 'subsample': 0.7}


In [20]:
xgb_tune = xgb_grid.estimator
 
xgb_tune.fit(X_train,y_train) # 0.9117591385438816
xgb_tune.score(X_test,y_test)

NameError: name 'xgb_grid' is not defined

In [22]:
cvs = cross_val_score(xgb_tune, X_train,y_train, cv = 10)
cvs, cvs.mean() #  0.9645582338461773)

(array([0.98991766, 0.98632505, 0.99685279, 0.98296558, 0.97656955,
        0.99525125, 0.97360094, 0.94556716, 0.99408487, 0.98854857]),
 0.9829683423733027)

In [23]:
xgb_grid.estimator

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.300000012, max_delta_step=0, max_depth=6,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=8, num_parallel_tree=1,
             objective='reg:squarederror', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method='exact',
             validate_parameters=1, verbosity=None)

In [24]:
xgb_tune2 =  XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=0.9, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.05, max_delta_step=0,
             max_depth=4, min_child_weight=5, missing=None, n_estimators=100,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)
xgb_tune2.fit(X_train,y_train) # 0.9412851220926807
xgb_tune2.score(X_test,y_test)

[23:34:02] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/objective/regression_obj.cu:170: reg:linear is now deprecated in favor of reg:squarederror.


0.8827628946002203

In [25]:
cvs = cross_val_score(xgb_tune2, X_train,y_train, cv = 5)
cvs, cvs.mean()

[23:34:04] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/objective/regression_obj.cu:170: reg:linear is now deprecated in favor of reg:squarederror.
[23:34:05] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/objective/regression_obj.cu:170: reg:linear is now deprecated in favor of reg:squarederror.
[23:34:06] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/objective/regression_obj.cu:170: reg:linear is now deprecated in favor of reg:squarederror.
[23:34:07] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/objective/regression_obj.cu:170: reg:linear is now deprecated in favor of reg:squarederror.
[23:34:09] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/objective/regression_obj.cu:170: reg:linear is now deprecated in favor of reg:squarederror.


(array([0.98009917, 0.98387919, 0.97911232, 0.90684722, 0.96806371]),
 0.9636003228149705)

In [26]:
np.sqrt(mean_squared_error(y_test, xgb_tune2.predict(X_test)))

48.534912823445694

## Test Model

In [27]:
X.columns

Index(['bath', 'balcony', 'total_sqft_int', 'bhk', 'price_per_sqft',
       'area_typeSuper built-up  Area', 'area_typeBuilt-up  Area',
       'area_typePlot  Area', 'availability_Ready To Move',
       'location_Whitefield',
       ...
       'location_Doddathoguru', 'location_Subramanyapura',
       'location_Hosur Road', 'location_Hebbal Kempapura',
       'location_Vidyaranyapura', 'location_BTM 2nd Stage',
       'location_Mahadevpura', 'location_Domlur',
       'location_Horamavu Banaswadi', 'location_Tumkur Road'],
      dtype='object', length=107)

In [ ]:
# it help to get predicted value of hosue  by providing features value 
def predict_house_price(model,bath,balcony,total_sqft_int,bhk,price_per_sqft,area_type,availability,location):
    
    x =np.zeros(len(X.columns)) # create zero numpy array, len = 107 as input value for model
 
    # adding feature's value accorind to their column index
    x[0]=bath
    x[1]=balcony
    x[2]=total_sqft_int
    x[3]=bhk
    x[4]=price_per_sqft
 
    if "availability"=="Ready To Move":
        x[8]=1
 
    if 'area_type'+area_type in X.columns:
        area_type_index = np.where(X.columns=="area_type"+area_type)[0][0]
        x[area_type_index] =1
 
        #print(area_type_index)
 
    if 'location_'+location in X.columns:
        loc_index = np.where(X.columns=="location_"+location)[0][0]
        x[loc_index] =1
 
        #print(loc_index)
 
    #print(x)
 
    # feature scaling
    x = sc.transform([x])[0] # give 2d np array for feature scaling and get 1d scaled np array
    x= np.array(x).reshape((1,-1))
    #print(x)

 
    return model.predict(x) # return the predicted value by train XGBoost model
 

In [29]:
predict_house_price(model=xgb_tune2, bath=3,balcony=2,total_sqft_int=1672,bhk=3,price_per_sqft=8870.291866,area_type="Plot  Area",availability="Ready To Move",location="Devarabeesana Halli")

array([145.1817], dtype=float32)

# Save model &amp; load model

In [30]:
import joblib
# save model
joblib.dump(xgb_tune2, 'bangalore_house_price_prediction_model.pkl')

['bangalore_house_price_prediction_model.pkl']

In [21]:
import joblib
joblib.dump(rfr, 'bangalore_house_price_prediction_rfr_model.pkl')

['bangalore_house_price_prediction_rfr_model.pkl']

In [31]:
# load model
bangalore_house_price_prediction_model = joblib.load("bangalore_house_price_prediction_model.pkl")

In [32]:
# predict house price
predict_house_price(bangalore_house_price_prediction_model,bath=2,balcony=2,total_sqft_int=2000,bhk=2,price_per_sqft=500,area_type="Built-up Area",availability="Ready To Move",location="Electronic City")

array([70.50888], dtype=float32)